multipart:
  max-file-size: 50MB
  max-request-size: 50MB
  location: ${java.io.tmpdir}
  
spring:
  mvc:
    favicon:
      enabled: false

server:
  port: 9090 
  
com.justgifit:
  optimize: true
  gif-location: ${java.io.tmpdir}/gif